version: 0.2

env:
  variables:
    GO111MODULE: "on"
    GO_VERSION: 1.20.1

phases:
  install:
    runtime-versions:
      golang: $GO_VERSION
    commands:
      - echo "Instalando dependencias de Go..."
      - go mod tidy
      - go get -v ./...
  pre_build:
    commands:
      - echo "Ejecutando pruebas integracion..."
      - go test ./internal/repository -coverprofile=coverage-report
      - go tool cover -html coverage-report -o coverage-report.html
  build:
    commands:
      - echo "Construyendo proyecto..."
      - go build -C ./cmd/app/ -o ../../bin/application.go
reports:
  coverage-report:
    files:
      - './coverage-report.html'
    file-format: 'HTML'

artifacts:
  files:
    - bin/application.go